# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlol.proto\"\x1c\n\x08Response\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x07\n\x05\x45mpty20\n\nRecognizer\x12\"\n\x0bGetResponse\x12\x06.Empty\x1a\t.Response\"\x00\x62\x06proto3')



_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'lol_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'lol_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_RECOGNIZER = DESCRIPTOR.services_by_name['Recognizer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSE._serialized_start=13
  _RESPONSE._serialized_end=41
  _EMPTY._serialized_start=43
  _EMPTY._serialized_end=50
  _RECOGNIZER._serialized_start=52
  _RECOGNIZER._serialized_end=100
# @@protoc_insertion_point(module_scope)
